on:
  pull_request:
  push:
  schedule:
    - cron: '* 3 * * 0' # every Sunday at 3 AM

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: azohra/shell-linter@v0.3.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker pull '${{ github.actor }}/aspell' || true
          docker build \
            --pull \
            --cache-from '${{ github.actor }}/aspell' \
            -t '${{ github.actor }}/aspell' \
            -f Dockerfile \
            .
      - name: Test Action
        uses: ./
        with:
          files: '**/*.md'
          args: '--lang=en_GB --mode=markdown'
      - name: Log into Docker Hub
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u '${{ github.actor }}' --password-stdin
      - name: Push Docker Image
        run: docker push '${{ github.actor }}/aspell'
